# Generated by Django 3.0.8 on 2020-07-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='Skill')),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(choices=[('0', 'Developer'), ('1', 'Administrator'), ('2', 'Support technician'), ('3', 'Web designer'), ('4', 'Others')], max_length=1, verbose_name='Job'),
        ),
    ]
