# Generated by Django 3.0.8 on 2020-07-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20200718_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cv',
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(choices=[('0', 'Developer'), ('1', 'Administrator'), ('2', 'Support technician'), ('3', 'Web designer'), ('4', 'Others')], max_length=1, verbose_name='Job'),
        ),
    ]
