# Generated by Django 3.0.8 on 2020-07-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_employee_full_lame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='full_lame',
            new_name='full_name',
        ),
    ]
