# Generated by Django 3.0.8 on 2020-07-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('short_name', models.CharField(max_length=20, verbose_name='Short Name')),
                ('anulate', models.BooleanField(default=False, verbose_name='Anulate')),
            ],
        ),
    ]
